-- GENERATED by scripts/generate-seed.mts from lib/content/*-seed.ts. Do not edit by hand.
-- Idempotent: existing rows (including organizer edits) are left untouched.

insert into public.event_items (slug, day, starts_at, ends_at, title, description_md, location_name, address, address_confirmed, choice_group, requires_payment, price_cents, allows_guests, capacity, confirmed, unconfirmed_note, halftime_eligible, visible, sort) values
  ('fri-tour-jacobs', '2027-10-08', '2027-10-08T15:30:00-05:00', '2027-10-08T16:30:00-05:00', 'School Tour — Jacobs', 'Walk the halls where the first Jacobs class finished.', 'Harry D. Jacobs High School', '2601 Bunker Hill Dr, Algonquin, IL 60102', true, 'fri_tour', false, null, true, null, true, null, false, true, 10),
  ('fri-tour-crown', '2027-10-08', '2027-10-08T15:30:00-05:00', '2027-10-08T16:30:00-05:00', 'School Tour — Crown', 'Walk the halls where it all started.', 'Irving Crown building (today Dundee-Crown High School)', '1500 Kings Rd, Carpentersville, IL 60110', true, 'fri_tour', false, null, true, null, true, null, false, true, 20),
  ('fri-pregame', '2027-10-08', '2027-10-08T17:00:00-05:00', null, 'Pre-Game Drink', 'Pay your own tab. The brewery has no kitchen on site — food trucks or outside food only.', 'Scorched Earth Brewing Co.', '203 Berg St, Algonquin, IL 60102', true, null, false, null, true, null, true, null, false, true, 30),
  ('fri-game-jacobs', '2027-10-08', '2027-10-08T19:00:00-05:00', null, 'Football: Jacobs vs. Prairie Ridge', 'Halftime recognition of the Class of ’77.', 'Jacobs High School', '2601 Bunker Hill Dr, Algonquin, IL 60102', true, 'fri_game', false, null, true, null, false, 'Schedule to be confirmed by the schools', true, true, 40),
  ('fri-game-crown', '2027-10-08', '2027-10-08T19:00:00-05:00', null, 'Football: Dundee-Crown vs. Crystal Lake South', 'Halftime recognition of the Class of ’77.', 'Dundee-Crown High School', '1500 Kings Rd, Carpentersville, IL 60110', true, 'fri_game', false, null, true, null, false, 'Schedule to be confirmed by the schools', true, true, 50),
  ('sat-golf', '2027-10-09', '2027-10-09T11:00:00-05:00', '2027-10-09T15:00:00-05:00', 'Golf', '', 'Randall Oaks Golf Club', '4101 Binnie Rd, West Dundee, IL 60118', true, 'sat_day', false, null, true, null, true, null, false, true, 60),
  ('sat-pickleball', '2027-10-09', '2027-10-09T11:00:00-05:00', '2027-10-09T15:00:00-05:00', 'Pickleball & Social', '', 'Pickle Haüs', '1621 S Randall Rd, Algonquin, IL 60102', true, 'sat_day', false, null, true, null, true, null, false, true, 70),
  ('sat-dinner', '2027-10-09', '2027-10-09T18:30:00-05:00', '2027-10-09T22:30:00-05:00', 'Reunion Dinner', 'Cash bar.', 'West Dundee VFW Post 2298', '117 S 1st St, West Dundee, IL 60118', false, null, true, null, true, null, false, 'Venue to be confirmed', false, true, 80),
  ('sun-brunch', '2027-10-10', null, null, 'Farewell Breakfast/Brunch', '', null, null, false, null, false, null, true, null, false, null, false, true, 90)
on conflict (slug) do nothing;

-- A setting still unset (null) picks up a newly decided default; set values are kept.
insert into public.settings (key, value, is_public) values
  ('rsvp_deadline', 'null'::jsonb, true),
  ('refund_policy_md', 'null'::jsonb, true),
  ('refund_cutoff_date', 'null'::jsonb, true),
  ('organizer_contact_email', '"reunion@crownjacobs77.com"'::jsonb, true),
  ('faq_md', 'null'::jsonb, true),
  ('feature_flags', '{"in_memoriam":false,"faq":false,"yearbook_ocr":true}'::jsonb, true),
  ('section_gate_enabled', 'true'::jsonb, false),
  ('section_gate_passcode_hash', 'null'::jsonb, false)
on conflict (key) do update set value = excluded.value
  where public.settings.value = 'null'::jsonb and excluded.value <> 'null'::jsonb;

-- Yearbooks: fill the seniors range only while unset (the organizer can edit it).
insert into public.yearbook_books (school, title, seniors_start_seq, seniors_end_seq) values
  ('jacobs', 'Eyrie 1977', 112, 123),
  ('crown', 'Valhallan 1977', 88, 103)
on conflict (school) do update set
  title = case when public.yearbook_books.title like '% — 1977' then excluded.title else public.yearbook_books.title end,
  seniors_start_seq = coalesce(public.yearbook_books.seniors_start_seq, excluded.seniors_start_seq),
  seniors_end_seq = coalesce(public.yearbook_books.seniors_end_seq, excluded.seniors_end_seq);
