// Static image imports (import x from "./photo.webp"). next-env.d.ts provides this
// too, but it is generated by `next build` and CI typechecks before building.
/// <reference types="next/image-types/global" />
