// Serves yearbook page images (pre-generated by scripts/ingest-yearbook.mts) only
// to URLs signed by the reunion site, so the scans stay behind the site's gates.
import { assetHeaders, verifySignedPath } from "./verify.js";

const worker = {
  /** @param {Request} request @param {{ ASSETS: { fetch: typeof fetch }, YEARBOOK_SIGNING_SECRET: string }} env */
  async fetch(request, env) {
    if (request.method !== "GET" && request.method !== "HEAD") return new Response("Method not allowed", { status: 405 });
    const url = new URL(request.url);
    const exp = url.searchParams.get("e");
    const ok = await verifySignedPath(url.pathname, exp, url.searchParams.get("s"), env.YEARBOOK_SIGNING_SECRET);
    if (!ok) return new Response("Not found", { status: 404, headers: { "X-Robots-Tag": "noindex" } });

    // Strip the signature so the asset lookup (and Cloudflare's cache key) is the bare path.
    const asset = await env.ASSETS.fetch(new Request(new URL(url.pathname, url.origin), request));
    if (!asset.ok) return new Response("Not found", { status: 404 });
    const response = new Response(asset.body, asset);
    for (const [name, value] of Object.entries(assetHeaders(exp))) response.headers.set(name, value);
    return response;
  },
};

export default worker;
