"""
Builds the home-hero portrait mosaic tiles from the senior portrait pages.

  python3 scripts/build-hero-mosaic.py [/path/to/crownjacobs77-yearbooks]

Finds faces on the senior pages (OpenCV), crops a square around each, tints
it in the school's duotone (Crown blues, Jacobs browns/golds) and packs the
tiles into one sprite: .yearbook-build/assets/hero/mosaic.webp + mosaic.json.
The sprite is served by the yearbook Worker (signed URLs), never committed:
it is derived from the scans. Needs: pip install opencv-python-headless pillow
"""
import json
import os
import sys

import cv2
import numpy as np
from PIL import Image

SRC = sys.argv[1] if len(sys.argv) > 1 else "/home/user/crownjacobs77-yearbooks"
OUT = ".yearbook-build/assets/hero"
TILE = 56  # px; drawn at ~20–36 CSS px, sharp on 2x screens
BOOKS = {
    # school: (folder, first senior seq, last senior seq) — seq = 1-based file order (lib/content/yearbook-seed.ts)
    "crown": ("crown-1977", 88, 103),
    "jacobs": ("jacobs-1977", 112, 123),
}
# Duotone ramps: shadow → highlight, in brand colors.
RAMPS = {
    "crown": ((8, 22, 52), (174, 202, 240)),  # deep navy → pale Crown blue
    "jacobs": ((36, 20, 6), (244, 196, 92)),  # deep brown → Jacobs gold
}

cascade = cv2.CascadeClassifier(os.path.join(cv2.data.haarcascades, "haarcascade_frontalface_default.xml"))
eyes = cv2.CascadeClassifier(os.path.join(cv2.data.haarcascades, "haarcascade_eye.xml"))


def duotone(gray, ramp):
    g = gray.astype(np.float32) / 255.0
    # Lift contrast a little so small tiles still read as faces.
    g = np.clip((g - 0.08) / 0.84, 0, 1) ** 0.9
    lo = np.array(ramp[0], np.float32)
    hi = np.array(ramp[1], np.float32)
    return (lo + (hi - lo) * g[..., None]).astype(np.uint8)


def faces_on(path):
    img = cv2.imread(path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    found = cascade.detectMultiScale(gray, scaleFactor=1.08, minNeighbors=6, minSize=(60, 60))
    if len(found) == 0:
        return []
    # Senior portraits share one size per page; candid photos and false hits don't.
    median = float(np.median([w for (_, _, w, _) in found]))
    crops = []
    for (x, y, w, h) in found:
        if not (0.7 * median <= w <= 1.35 * median):
            continue
        # A real face has at least one detectable eye in its upper half (drops signs, prints, text).
        upper = gray[y : y + h * 2 // 3, x : x + w]
        if len(eyes.detectMultiScale(upper, scaleFactor=1.05, minNeighbors=2, minSize=(w // 12, w // 12))) == 0:
            continue
        cx, cy = x + w / 2, y + h * 0.55
        half = w * 0.85  # a little hair and collar around the face
        x0, y0 = int(max(cx - half, 0)), int(max(cy - half, 0))
        x1, y1 = int(min(cx + half, gray.shape[1])), int(min(cy + half, gray.shape[0]))
        crop = gray[y0:y1, x0:x1]
        if crop.shape[0] < 40 or crop.shape[1] < 40:
            continue
        crops.append(cv2.resize(crop, (TILE, TILE), interpolation=cv2.INTER_AREA))
    return crops


tiles = {}
for school, (folder, first, last) in BOOKS.items():
    files = sorted(f for f in os.listdir(os.path.join(SRC, folder)) if f.lower().endswith((".jpg", ".jpeg", ".png")))
    out = []
    for seq in range(first, last + 1):
        out += faces_on(os.path.join(SRC, folder, files[seq - 1]))
    tiles[school] = [duotone(t, RAMPS[school]) for t in out]
    print(f"{school}: {len(out)} portraits from {last - first + 1} pages")

ordered = tiles["crown"] + tiles["jacobs"]
cols = 24
rows = (len(ordered) + cols - 1) // cols
sheet = Image.new("RGB", (cols * TILE, rows * TILE), (0, 0, 0))
for i, t in enumerate(ordered):
    sheet.paste(Image.fromarray(t), ((i % cols) * TILE, (i // cols) * TILE))
os.makedirs(OUT, exist_ok=True)
sheet.save(os.path.join(OUT, "mosaic.webp"), "WEBP", quality=62, method=6)
meta = {"tile": TILE, "cols": cols, "crown": len(tiles["crown"]), "jacobs": len(tiles["jacobs"])}
with open(os.path.join(OUT, "mosaic.json"), "w") as f:
    json.dump(meta, f)
# Just the numbers (no images) go in the repo, so the site knows how to cut the sprite.
with open("lib/content/hero-mosaic.ts", "w") as f:
    f.write("// Generated by scripts/build-hero-mosaic.py — the sprite itself lives on the yearbook Worker.\n")
    f.write(f"export const HERO_MOSAIC = {json.dumps(meta)} as const;\n")
print(meta, os.path.getsize(os.path.join(OUT, "mosaic.webp")), "bytes")
