/**
 * Builds the senior-class roster (public.classmates) from the OCR text of the
 * senior portrait pages, for the classmate check on RSVPs and /yearbooks.
 * Run after `ingest-yearbook.mts --ocr`. Writes .yearbook-build/roster.json and
 * .yearbook-build/roster.sql (idempotent). OCR misses and misreads are expected:
 * an unmatched RSVP is never rejected, only held for the organizer's one-click approval.
 *
 *   node scripts/extract-roster.mts
 */
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { YEARBOOK_BOOKS_SEED, type YearbookSchool } from "../lib/content/yearbook-seed.ts";

const OUT = ".yearbook-build";

// "Donna Coleman", "Mary Jo Smith", "Tina De Bartolo", "Robert O'Brien Jr."
const NAME = /^([A-Z][a-z]+(?:[- ][A-Z][a-z]+)?|[A-Z][a-z]+ [A-Z]\.)\s+((?:(?:De|Del|Di|La|Le|Van|Von|Mc|Mac|O')\s?)?[A-Z][A-Za-z'’-]+)(?:,?\s+(Jr|Sr|II|III)\.?)?$/;
// Words that look like names in captions/headings but aren't people.
const NOT_NAMES = /\b(Senior|Seniors|Class|Junior|High|School|Club|Council|Team|Board|Society|Crown|Jacobs|Eagles|Vikings|The|And|Of|Most|Likely|Best|National|Honor)\b/;

export interface RosterEntry {
  school: YearbookSchool;
  firstName: string;
  lastName: string;
  seq: number;
}

function namesFrom(text: string): Array<{ first: string; last: string }> {
  const found: Array<{ first: string; last: string }> = [];
  for (const raw of text.split("\n")) {
    const line = raw.replace(/[‘’`]/g, "'").replace(/\s+/g, " ").trim();
    if (line.length < 5 || line.length > 40 || NOT_NAMES.test(line)) continue;
    const m = NAME.exec(line);
    if (!m) continue;
    const last = m[2].replace(/\s+/g, " ");
    if (last.replace(/[^A-Za-z]/g, "").length < 2) continue;
    found.push({ first: m[1], last });
  }
  return found;
}

const roster: RosterEntry[] = [];
for (const book of YEARBOOK_BOOKS_SEED) {
  const seen = new Set<string>();
  for (let seq = book.seniorsStartSeq; seq <= book.seniorsEndSeq; seq++) {
    const text = await readFile(join(OUT, "ocr", `${book.school}-${seq}.txt`), "utf8").catch(() => "");
    for (const { first, last } of namesFrom(text)) {
      const key = `${first} ${last}`.toLowerCase();
      if (seen.has(key)) continue;
      seen.add(key);
      roster.push({ school: book.school, firstName: first, lastName: last, seq });
    }
  }
  console.log(`${book.school}: ${seen.size} names from pages ${book.seniorsStartSeq}–${book.seniorsEndSeq}`);
}

await writeFile(join(OUT, "roster.json"), JSON.stringify(roster, null, 1));
const q = (v: string) => `'${v.replace(/'/g, "''")}'`;
const sql = `-- Generated by scripts/extract-roster.mts (OCR of senior pages). Re-runnable.
insert into public.classmates (school, first_name, last_name, yearbook_page_id, source)
select v.school::public.yearbook_school, v.first_name, v.last_name, p.id, 'ocr'
from (values
${roster.map((r) => `  (${q(r.school)}, ${q(r.firstName)}, ${q(r.lastName)}, ${r.seq})`).join(",\n")}
) as v (school, first_name, last_name, seq)
left join public.yearbook_pages p on p.school = v.school::public.yearbook_school and p.seq = v.seq
on conflict (school, first_name, last_name) do nothing;
`;
await writeFile(join(OUT, "roster.sql"), sql);
console.log(`wrote ${roster.length} names → ${OUT}/roster.json, ${OUT}/roster.sql`);
