/**
 * Writes supabase/seed.sql from the typed seed modules, so SPEC §6 facts live
 * in exactly one place. Idempotent SQL: re-running never overwrites edits the
 * organizer has made in the database. Run: npm run db:seed:generate
 */
import { writeFile } from "node:fs/promises";
import { EVENT_ITEMS_SEED } from "../lib/content/event-seed.ts";
import { SETTINGS_SEED } from "../lib/content/settings-seed.ts";

const lit = (v: string | number | boolean | null): string => {
  if (v === null) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return String(v);
  return `'${v.replace(/'/g, "''")}'`;
};

const eventColumns = [
  "slug", "day", "starts_at", "ends_at", "title", "description_md", "location_name", "address",
  "address_confirmed", "choice_group", "requires_payment", "price_cents", "allows_guests", "capacity",
  "confirmed", "unconfirmed_note", "halftime_eligible", "visible", "sort",
];

const eventRows = EVENT_ITEMS_SEED.map((e) =>
  [
    e.slug, e.day, e.startsAt, e.endsAt, e.title, e.descriptionMd, e.locationName, e.address,
    e.addressConfirmed, e.choiceGroup, e.requiresPayment, e.priceCents, e.allowsGuests, e.capacity,
    e.confirmed, e.unconfirmedNote, e.halftimeEligible, e.visible, e.sort,
  ]
    .map(lit)
    .join(", "),
);

const settingsRows = SETTINGS_SEED.map(
  (s) => `(${lit(s.key)}, ${lit(JSON.stringify(s.value))}::jsonb, ${lit(s.isPublic)})`,
);

const sql = `-- GENERATED by scripts/generate-seed.mts from lib/content/*-seed.ts. Do not edit by hand.
-- Idempotent: existing rows (including organizer edits) are left untouched.

insert into public.event_items (${eventColumns.join(", ")}) values
${eventRows.map((r) => `  (${r})`).join(",\n")}
on conflict (slug) do nothing;

insert into public.settings (key, value, is_public) values
${settingsRows.map((r) => `  ${r}`).join(",\n")}
on conflict (key) do nothing;

insert into public.yearbook_books (school, title) values
  ('crown', 'Irving Crown High School — 1977'),
  ('jacobs', 'Harry D. Jacobs High School — 1977')
on conflict (school) do nothing;
`;

await writeFile("supabase/seed.sql", sql);
console.log(`Wrote supabase/seed.sql (${EVENT_ITEMS_SEED.length} event items, ${SETTINGS_SEED.length} settings)`);
